### ISSUE TITLE
lack of information

### ISSUE THREAD

**Issue by 0thna** [MysticJourney77/payday3-black-market#2]
what do you mean by creditentials, like username and password ? it seems thats the python code needs user id and access token, I am unable to use it because of the lack of steps in your readme file I got this error constantly : ![Capture d'écran 2023-10-16 190807](https://github.com/MysticJourney77/payday3-black-market/assets/134337743/dbf9e75d-0a9b-434f-aaf4-58670eca3746)

**Comment by XxRagulxX** [comment]
Hi @0thna, FYI You need to enter your Nebula account email and password .

**Comment by MysticJourney77** [comment]
Resolved
